version: '3.8'

services:
  tomcat:
    build: ./app
    container_name: tomcat-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tomcat
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
